# Um breve resumo do NumPy

- Gabriel Wendell Celestino Rocha.
- 29 de Novembro de 2022.

---

## 0. Preliminares

### 0.1 O que é o `NumPy` 

- `NumPy`: *Numerical Python*.

- `NumPy` é uma biblioteca Python usada para trabalhar com arrays.

- Possui funções para trabalhar no domínio da álgebra linear, transformada de Fourier e matrizes.

- Criado em 2005 por Travis Oliphant. É um projeto de código aberto e você pode usá-lo livremente.

- O `NumPy` é escrita parcialmente em Python, mas a maioria das partes que requerem computação rápida são escritas em C ou C++.

### 0.2 Por que usar o `NumPy`?

- Em Python, temos listas que servem ao propósito de arrays, mas são lentas para processar.

- O `NumPy` visa fornecer um objeto de matriz até 50 vezes mais rápido que as listas tradicionais do Python.

- O objeto array no `NumPy` é chamado `ndarray`, ele fornece muitas funções de suporte que facilitam muito o trabalho com o `ndarray`.

- Arrays são muito usados em ciência de dados, onde velocidade e recursos são muito importantes.

### 0.3 Por que o `NumPy` é mais rápido que as listas?

- As matrizes `NumPy` são armazenadas em um local contínuo na memória, ao contrário das listas, para que os processos possam acessá-las e manipulá-las com muita eficiência.

- Esse comportamento é chamado de *localidade de referência* em ciência da computação.

- Esta é a principal razão pela qual o `NumPy` é mais rápido que as listas. Também é otimizado para trabalhar com as arquiteturas de CPU mais recentes.

---

## 1. Instalação

- **CONDA**

Se você usar o `conda`, poderá instalar o `NumPy` a partir dos canais `default` ou do `conda-forge`:

> `default`:

```Python
$ conda create -n my-env
$ conda activate my-env
```
> `conda-forge`:

``` Python
$ conda config --env --add channels conda-forge
$ conda install numpy
```

- **PIP**

Se você usar `pip`, poderá instalar o `NumPy` com:

``` Python
$ pip install numpy
```

Além disso, ao usar o `pip`, é uma boa prática usar um *virtual enviroment* - consulte as documentações das [Instalações Reproduzíveis](https://numpy.org/install/#reproducible-installs) para saber o motivo e este [guia](https://dev.to/bowmanjd/python-tools-for-managing-virtual-environments-3bko#howto) para obter detalhes sobre o uso de ambientes virtuais.

---

## 2. Pondo o `NumPy` em prática

Para todo tipo de dúvidas e informações adicionais, veja a documentação [aqui](https://numpy.org/doc/stable/), em especial o pequeno tutorial [aqui](https://numpy.org/doc/stable/user/quickstart.html). Começamos importando a biblioteca do `NumPy` e a string da versão é armazenada no atributo `__version__`:

In [1]:
import numpy as np

print('Versão do NumPy =', np.__version__)

Versão do NumPy = 1.21.6


### 2.1 Trabalhando com arrays

#### 2.1.1 Construção de arrays

- Arrays simples:

In [2]:
np.array([0, 1, 2, 3, 4])

np.array([3.14, 1, 2, 3])

array([3.14, 1.  , 2.  , 3.  ])

- Arrays espaçados:

In [3]:
np.array([0.5, 1.5], dtype = 'float32')

np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

- Arrays linearmente espaçados:

In [4]:
np.linspace(0.5, 100.5, 101)

array([  0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,
         9.5,  10.5,  11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,
        18.5,  19.5,  20.5,  21.5,  22.5,  23.5,  24.5,  25.5,  26.5,
        27.5,  28.5,  29.5,  30.5,  31.5,  32.5,  33.5,  34.5,  35.5,
        36.5,  37.5,  38.5,  39.5,  40.5,  41.5,  42.5,  43.5,  44.5,
        45.5,  46.5,  47.5,  48.5,  49.5,  50.5,  51.5,  52.5,  53.5,
        54.5,  55.5,  56.5,  57.5,  58.5,  59.5,  60.5,  61.5,  62.5,
        63.5,  64.5,  65.5,  66.5,  67.5,  68.5,  69.5,  70.5,  71.5,
        72.5,  73.5,  74.5,  75.5,  76.5,  77.5,  78.5,  79.5,  80.5,
        81.5,  82.5,  83.5,  84.5,  85.5,  86.5,  87.5,  88.5,  89.5,
        90.5,  91.5,  92.5,  93.5,  94.5,  95.5,  96.5,  97.5,  98.5,
        99.5, 100.5])

- Matriz Identidade:

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- Array de valor único:

In [6]:
np.full(5, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14])

- Array de valores unitários:

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

- Array de valores nulos:

In [8]:
np.zeros(5)

np.empty(5)

array([0., 0., 0., 0., 0.])

#### 2.1.2 Propriedades básicas

- Tipo de array:

In [9]:
a = np.arange(10)
type(a)

numpy.ndarray

- Forma do array:

In [10]:
print('Shape(a) =', a.shape)

b = np.eye(5)
print('Shape(b) =', b.shape)

Shape(a) = (10,)
Shape(b) = (5, 5)


- Dimensão do array:

In [11]:
print('Dim(a) =', a.ndim)
print('Dim(b) =', b.ndim)

Dim(a) = 1
Dim(b) = 2


- Tamanho do array:

In [12]:
print('Size(a) =', a.size)
print('Size(b) =', b.size)

Size(a) = 10
Size(b) = 25


- Definindo sub-arrays:

In [13]:
print('a[2:5] =', a[2:5])

a[1] = 11
print('a[1] =', a)

a[2:5] = [-1, -2, -3]
print('a[2:5] =', a)

a[2:5] = [2 3 4]
a[1] = [ 0 11  2  3  4  5  6  7  8  9]
a[2:5] = [ 0 11 -1 -2 -3  5  6  7  8  9]


In [14]:
print(b)
print('')

print('b[0][0] =', b[0][0])

print('b[0, 0] =', b[0, 0])

print('b[0, :] =', b[0, :])

print('b[:, -1] =', b[:, -1])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

b[0][0] = 1.0
b[0, 0] = 1.0
b[0, :] = [1. 0. 0. 0. 0.]
b[:, -1] = [0. 0. 0. 0. 1.]


- Concatenação de arrays:

In [15]:
print('Concatenação:', np.concatenate([np.arange(1, 4), [4, 5, 6]]))

np.hstack, np.stack

Concatenação: [1 2 3 4 5 6]


(<function numpy.hstack(tup)>,
 <function numpy.stack(arrays, axis=0, out=None)>)

In [16]:
np.concatenate?

- Separação de arrays

In [17]:
np.split(a, [3, 5])

[array([ 0, 11, -1]), array([-2, -3]), array([5, 6, 7, 8, 9])]

In [18]:
x, y, z = np.split(a, [3, 5])

print('x =', x)
print('y =', y)
print('z =', z)

x = [ 0 11 -1]
y = [-2 -3]
z = [5 6 7 8 9]


### 2.2 Computação prática

- Funções universais:

In [19]:
def sqrt(a):
    b = np.empty(a.size)
    for i in range(a.size):
        b[i] = a[i] ** (1/2)
        
    return b

sqrt(np.arange(10))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

- Notação científica:

In [20]:
print('Array de floats:', np.zeros(int(1.5e6)))

Array de floats: [0. 0. 0. ... 0. 0. 0.]


- Tempo de execução:

In [21]:
Big_array = np.arange(1_000_000)
Big_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [22]:
%timeit sqrt(Big_array)

2.88 s ± 6.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
%timeit Big_array ** (1/2)

50 ms ± 628 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
%timeit np.sqrt(Big_array)

4.79 ms ± 544 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


- Arrays de números aleatórios:

In [25]:
rng = np.random.default_rng(42)
rng.integers(0, 10, 5)

array([0, 7, 6, 4, 4], dtype=int64)

**Distribuição Normal**

$$p(x) = \frac{1}{\sqrt{ 2 \pi \sigma^2 }}\cdot \exp{\Bigg[{ - \frac{ (x - \mu)^2 } {2 \sigma^2} }\Bigg]}$$

**Distribuição Gamma**

$$p(x) = x^{k-1}\cdot\frac{e^{-x/\theta}}{\theta^k\Gamma(k)}$$

**Distribuição de Poisson**

$$f(k; \lambda)=\frac{\lambda^k e^{-\lambda}}{k!}$$

In [26]:
print('Normal:', rng.normal(1, 2.5, 10))

print('')

print('Gamma:', rng.gamma(1, 5.7, 10))

print('')

print('Poisson:', rng.poisson(11.11, 10))

Normal: [ 3.35141179 -3.87758797 -2.25544877  1.31960101  0.20939352  0.95799711
 -1.13260982  3.19849494  2.94447984  1.16507674]

Gamma: [ 2.2053005   7.02003828  0.87650755  0.52199042  1.79652145  5.13683587
  2.35401638  7.11009991  1.27438532 10.47643051]

Poisson: [ 8  3 13 20 10  8 11 13  9 14]


In [27]:
a = rng.random(10)
b = rng.random(10)

print('a + b =', np.add(a, b))

a + b = [0.8570693  0.8222925  0.25428256 0.86831116 0.47845848 1.35216048
 1.42984971 1.3398837  1.33430843 1.01812294]


- Operações boolenas:

In [28]:
c = np.arange(3)
print('c =', c)

print('np.any(c) =', np.any(c))

print('np.all(c) =', np.all(c))

c = [0 1 2]
np.any(c) = True
np.all(c) = False


- Estatística:

In [29]:
print('Média =', np.mean(a)) 
print('')

print('Mediana =', np.median(a))
print('')

print('Desvio Padrão =', np.std(b))
print('')

print('Variância =', np.var(b))

Média = 0.47144319830214576

Mediana = 0.561883316065186

Desvio Padrão = 0.20275515967788155

Variância = 0.04110965477600324


- Soma de linhas e colunas de uma matriz:

In [30]:
d = np.array([[0, 1], [-2, 0.5], [np.pi, np.e]])
print(d)
print('')

print('sum(d, axis = 0) =', np.sum(d, axis = 0))
print('')

print('sum(d, axis = 1) =', np.sum(d, axis = 1))
print('')

print('max(d, axis = 1) =', np.max(d, axis = 1))

[[ 0.          1.        ]
 [-2.          0.5       ]
 [ 3.14159265  2.71828183]]

sum(d, axis = 0) = [1.14159265 4.21828183]

sum(d, axis = 1) = [ 1.         -1.5         5.85987448]

max(d, axis = 1) = [1.         0.5        3.14159265]


- Funções matemáticas em arrays:

In [31]:
print('a =', a)

print('\nsin(a) =', np.sin(a))

print('\nlog10(a) =', np.log10(a))

print('\nln(a) =', np.log(a))

print('\nexp(a) =', np.exp(a))

a = [0.2883281  0.6824955  0.13975248 0.1999082  0.00736227 0.78692438
 0.66485086 0.70516538 0.78072903 0.45891578]

sin(a) = [0.28434974 0.6307315  0.13929802 0.19857936 0.0073622  0.70818515
 0.61694176 0.64815977 0.70379751 0.44297632]

log10(a) = [-0.54011302 -0.16590021 -0.85464047 -0.69916939 -2.13298827 -0.104067
 -0.17727577 -0.15170902 -0.10749967 -0.33826701]

ln(a) = [-1.2436562  -0.38199934 -1.9678824  -1.60989701 -4.911387   -0.23962312
 -0.40819254 -0.34932292 -0.24752714 -0.77888858]

exp(a) = [1.33419499 1.9788097  1.14998912 1.22129064 1.00738944 2.19663002
 1.94420054 2.02418141 2.18306321 1.58235742]


- Mensagens de erros:

In [32]:
np.arccos(2)

C:\Users\Gabriel Wendell\AppData\Local\Temp\ipykernel_13212\2173637614.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(2)


nan

In [33]:
1/np.arange(10)

C:\Users\Gabriel Wendell\AppData\Local\Temp\ipykernel_13212\4242892561.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/np.arange(10)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [34]:
-1/np.arange(10)

C:\Users\Gabriel Wendell\AppData\Local\Temp\ipykernel_13212\593241902.py:1: RuntimeWarning: divide by zero encountered in true_divide
  -1/np.arange(10)


array([       -inf, -1.        , -0.5       , -0.33333333, -0.25      ,
       -0.2       , -0.16666667, -0.14285714, -0.125     , -0.11111111])

- Relações de equivalência:

In [35]:
np.greater(a, b)

array([False,  True,  True, False, False,  True, False,  True,  True,
       False])

In [36]:
a > b

array([False,  True,  True, False, False,  True, False,  True,  True,
       False])

### 2.3 Máscaras e *fancy indexing*

In [37]:
print('a =', a)

print('\na[0] =', a[0], '\na[2] =', a[2], '\na[4] =', a[4], '\na[6] =', a[6], '\na[8] =', a[8])

a = [0.2883281  0.6824955  0.13975248 0.1999082  0.00736227 0.78692438
 0.66485086 0.70516538 0.78072903 0.45891578]

a[0] = 0.2883281039302441 
a[2] = 0.1397524836093098 
a[4] = 0.007362269751005512 
a[6] = 0.6648508565920321 
a[8] = 0.7807290310219679


In [38]:
print('a[::2] =', a[::2])

print('\na[1::2]', a[1::2])

a[::2] = [0.2883281  0.13975248 0.00736227 0.66485086 0.78072903]

a[1::2] [0.6824955  0.1999082  0.78692438 0.70516538 0.45891578]


In [39]:
x = rng.normal(0, 1, 20)
print('x =', x)

x > 0

x = [ 0.79334724 -0.34872507 -0.46235179  0.85797588 -0.19130432 -1.27568632
 -1.13328721 -0.91945229  0.49716074  0.14242574  0.69048535 -0.42725265
  0.15853969  0.62559039 -0.30934654  0.45677524 -0.66192594 -0.36305385
 -0.38173789 -1.19583965]


array([ True, False, False,  True, False, False, False, False,  True,
        True,  True, False,  True,  True, False,  True, False, False,
       False, False])

In [40]:
mask = x > 0
print('mask =', mask)

print('\nx[mask] =', x[mask])

print('\nx[[0, 2, 4, 6, 8]] =', x[[0, 2, 4, 6, 8]])

mask = [ True False False  True False False False False  True  True  True False
  True  True False  True False False False False]

x[mask] = [0.79334724 0.85797588 0.49716074 0.14242574 0.69048535 0.15853969
 0.62559039 0.45677524]

x[[0, 2, 4, 6, 8]] = [ 0.79334724 -0.46235179 -0.19130432 -1.13328721  0.49716074]


---

**BÔNUS**

In [41]:
try:
    import numpy as np
    import Blah

except:
    print('Not import')

Not import


---